### ISSUE TITLE
axios error

### ISSUE THREAD

**Issue by pingji00** [susanBuck/e28-fall19#123]
Axios seems was installed correctly at first, then for some reason, it's gone later.  Here's the info from Terminal, any suggestions? Many thanks!

```
/Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods (master) ! $ npm install axios
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.

+ axios@0.19.0
updated 1 package and audited 26575 packages in 4.307s
found 0 vulnerabilities

/Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods (master) ! $ npm run serve

> zipfoods@0.1.0 serve /Applications/XAMPP/xamppfiles/htdocs/e28/zipfoods
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 1892ms                                                2:02:52 PM


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: unavailable

  Note that the development build is not optimized.
  To create a production build, run npm run build.



 WAIT  Compiling...                                                                   2:06:52 PM

98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                               2:06:53 PM

 error  in ./src/App.vue

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'axios' is not defined (no-undef) at src/App.vue:29:5:
  27 |   },
  28 |   mounted() {
> 29 |     axios
     |     ^
  30 |       .get('https://my-json-server.typicode.com/pingji00/e28-zipfoods-api/products')
  31 |       .then(response => {
  32 |           console.log(response);


1 error found.

 @ ./src/main.js 6:0-28 39:13-16
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js



 WAIT  Compiling...                                                                   2:08:06 PM

98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                               2:08:07 PM

 error  in ./src/App.vue

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'axios' is not defined (no-undef) at src/App.vue:29:5:
  27 |   },
  28 |   mounted() {
> 29 |     axios
     |     ^
  30 |       .get('https://my-json-server.typicode.com/pingji00/e28-zipfoods-api/products')
  31 |       .then(response => {
  32 |           console.log(response);


1 error found.

 @ ./src/main.js 6:0-28 39:13-16
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js


```

Weird. 
After cancel and run `npm run build` again, the error in the Terminal disappeared, but in the browser's console, it still shows `vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook: "ReferenceError: axios is not defined"`

**Comment by susanBuck** [comment]
I suspect that Axios is installed - but maybe your script isn't including it?

```
const axios = require('axios');
```

**Comment by pingji00** [comment]
Thank you! it turns out I was missing to import it in the script
