### ISSUE TITLE
Error when copying P3 to P4 following instructions in notes

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/e28-fall19#152]
Hi all. I followed the instructions in the notes to copy P3 to the P4 folder but keep running into an odd error. I performed the following from my E28 folder:
```
$ cp -r p3 p4
$ cd p4
$ rm -rf node_modules
$ npm install
```
When a do this: `npm run serve` though, I get the following error:
```
λ npm run serve

> p4@0.1.0 serve D:\Development\xampp\htdocs\e28\p4
> vue-cli-service serve

 INFO  Starting development server...
10% building 6/9 modules 3 active D:\Development\xampp\htdocs\e28\p4\node_modules\webpack\hot\emitter.jsevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available 23.202.231.169:8080
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p4@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p4@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jerry\AppData\Roaming\npm-cache\_logs\2019-11-26T21_55_54_437Z-debug.log
```
The debug log doesn't really provide any additional information. Any ideas? Thanks.

**Comment by gaderrick** [comment]
Ooops. I'll leave this up here for a couple of days, but I figured it out. I forgot to add "p4.loc" to my hosts file.
